[project]
name = "qosst-hal"
description = "Hardware Abstraction Layer (HAL) submodule of QOSST"
authors = [
  { name = "Yoann Piétri", email = "Yoann.Pietri@lip6.fr" },
  { name = "Thomas Liege", email = "Thomas.Liege@lip6.fr" },
]

license = "GPLv3"
readme = "README.md"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Security :: Cryptography",
]
requires-python = ">=3.9,<3.14"
dependencies = [
  "numpy >=1.26.0, <2.0 ; python_version >= '3.9' and python_version < '3.11'",
  "numpy >=2.2.0, <3.0 ; python_version >= '3.11' and python_version < '3.14'",
]
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/qosst"
repository = "https://github.com/qosst/qosst-hal"
documentation = "https://qosst-hal.readthedocs.io/"


[tool.poetry]
version = "0.10.0.dev0"
packages = [{ include = "qosst_hal" }, { include = "qosst_hal/py.typed" }]


[tool.poetry.group.dev.dependencies]
Sphinx = [
  { version = "^5.0.0", python = ">=3.9, <3.10" },
  { version = "^8.1.0", python = ">=3.10, <3.14" },
]
sphinx-rtd-theme = [
  { version = "^1.0.0", python = ">=3.9, <3.10" },
  { version = "^3.0.0", python = ">=3.10, <3.14" },
]
sphinx-prompt = "^1.5.0"
myst-parser = [
  { version = "^1.0.0", python = ">=3.9, <3.10" },
  { version = "^4.0.0", python = ">=3.10, <3.14" },
]
setuptools = "^67.6.1"
docstr-coverage = "^2.2.0"
pylint = "^3.3.0"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
