[project]
name = "qosst-hal"
description = "Hardware Abstraction Layer (HAL) submodule of QOSST"
authors = [
  { name = "Yoann Piétri", email = "Yoann.Pietri@lip6.fr" },
  { name = "Thomas Liege", email = "Thomas.Liege@lip6.fr" },
]

license = "GPL-3.0-only"
readme = "README.md"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Security :: Cryptography",
]
requires-python = ">=3.11,<3.15"
dependencies = [
  "numpy >=2.2.0, <3.0",
]
version = "0.10.0.dev3"

[project.urls]
homepage = "https://github.com/qosst"
repository = "https://github.com/qosst/qosst-hal"
documentation = "https://qosst-hal.readthedocs.io/"


[tool.poetry]
packages = [{ include = "qosst_hal" }, { include = "qosst_hal/py.typed" }]


[dependency-groups]
dev = [
  "Sphinx>=8.1.0",
  "sphinx-rtd-theme>=3.0.0",
  "sphinx-prompt>=1.5.0",
  "myst-parser>=4.0.0",
  "setuptools>=67.6.1",
  "docstr-coverage>=2.2.0",
  "pylint>=3.3.0",
  "black>=26.5.1",
  "mypy>=2.3.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["qosst_hal/"]

[tool.hatch.build.targets.wheel.force-include]
"qosst_hal/py.typed" = "qosst_hal/py.typed"
